[package]
name = "mw3-settings-tool"
version = "0.1.0"
edition = "2021"

[package.metadata.windows]
subsystem = "windows"

[dependencies]
eframe = { version = "0.24.0", features = ["default_fonts", "persistence"] }
egui = "0.24.0"
rfd = "0.11"
serde_json = "1.0"
chrono = "0.4"
dirs = "4.0"
winapi = { version = "0.3", features = ["winuser", "shellapi", "impl-default"] }